version: '3.8'

services:
  backend:
    build:
      context: ./Services
      dockerfile: dockerfile
    container_name: backend-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: IOT_Project
    restart: always

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: IOT_Project
      MYSQL_USER: Test
      MYSQL_PASSWORD: Password
    volumes:
      - db_data:/var/lib/mysql
    # - ./db-init:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
volumes:
  db_data: